version: '3.1'


services:
   db:
     image: mysql:5.7
     volumes:
       - /home/nishant.singh/Desktop/Dockercomposephp/mysql_php:/var/lib/mysql
     networks:
       - active-hub
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somephp 
       MYSQL_DATABASE: php
       MYSQL_USER: php
       MYSQL_PASSWORD: php


   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin
     ports:
       - "8080:80"
     restart: always
     environment:
       PHP_DB_HOST: db:3306
       PHP_DB_USER: php
       PHP_DB_PASSWORD: php
       PHP_DB_NAME: php
     networks:
       - active-hub

volumes:
    db_data:
networks:
    active-hub: